-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Asurans\Downloads\fac\tese\grain window hdl coder\codegen\window_v4\hdlsrc\window_v4_fixpt_pkg.vhd
-- Created: 2024-03-03 15:41:04
-- 
-- Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE window_v4_fixpt_pkg IS
  TYPE vector_of_signed55 IS ARRAY (NATURAL RANGE <>) OF signed(54 DOWNTO 0);
  TYPE vector_of_unsigned53 IS ARRAY (NATURAL RANGE <>) OF unsigned(52 DOWNTO 0);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END window_v4_fixpt_pkg;

