%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
%CC_attack and CC_release are MIDI CC parameters which can vary between
%0-127 where 0=0% and 127=50%
function out = window_v4_fixpt(CC_attack, CC_release,current,size,in)
    fm = get_fimath();

    persistent interrim_1;
    if isempty(interrim_1)
        interrim_1 = fi(1, 1, 28, 0, fm);
    end
    persistent interrim_2;
    if isempty(interrim_2)
        interrim_2 = fi(1, 1, 28, 0, fm);
    end
    
    attack = fi(floor((CC_attack+fi(1, 0, 1, 0, fm))*fi(1/255, 0, 16, 23, fm) *size)+fi(1, 0, 1, 0, fm), 0, 12, 0, fm);
    release = fi(floor((CC_release+fi(1, 0, 1, 0, fm))*fi(1/255, 0, 16, 23, fm) *size)+fi(1, 0, 1, 0, fm), 0, 12, 0, fm);
    
    if current <= attack
        interrim_1(:) = (current-fi(1, 0, 1, 0, fm)) *in;
        out = fi(fi_div(interrim_1, attack), 1, 16, 0, fm);
    elseif current < size - release
        out = fi(in, 1, 16, 0, fm);
    else
        %out = (size - current) /release *in;
        interrim_2(:) = (size-current) *in;
        out = fi(fi_div(interrim_2, release), 1, 16, 0, fm);
    end
end



function ntype = divideType(a,b)
    coder.inline( 'always' );
    nt1 = numerictype( a );
    nt2 = numerictype( b );
    maxFL = max( [ min( nt1.WordLength, nt1.FractionLength ), min( nt2.WordLength, nt2.FractionLength ) ] );
    FL = max( maxFL, 24 );
    extraBits = (FL - maxFL);
    WL = nt1.WordLength + nt2.WordLength;
    WL = min( WL, 124 );
    if (WL + extraBits)<64
        ntype = numerictype( nt1.Signed || nt2.Signed, WL + extraBits, FL );
    else
        ntype = numerictype( nt1.Signed || nt2.Signed, WL, FL );
    end
end


function c = fi_div(a,b)
    coder.inline( 'always' );
    a1 = fi( a, 'RoundMode', 'fix' );
    b1 = fi( b, 'RoundMode', 'fix' );
    nType = divideType( a1, b1 );
    if isfi( a ) && isfi( b ) && isscalar( b )
        c1 = divide( nType, a1, b1 );
        c = fi( c1, numerictype( c1 ), fimath( a ) );
    else
        c = fi( a / b, nType );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
