%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function ASR_OUT = ASR_GEN_wrapper_fixpt(ATTACK_CC,RELEASE_CC,MAX_ATTACK_MS,MAX_RELEASE_MS,CLK_FREQ,NOTE_ON,ASR_IN)
    fm = get_fimath();
    ATTACK_CC_in = fi( ATTACK_CC, 0, 7, 0, fm );
    RELEASE_CC_in = fi( RELEASE_CC, 0, 7, 0, fm );
    MAX_ATTACK_MS_in = fi( MAX_ATTACK_MS, 0, 10, 0, fm );
    MAX_RELEASE_MS_in = fi( MAX_RELEASE_MS, 0, 10, 0, fm );
    CLK_FREQ_in = fi( CLK_FREQ, 0, 27, 0, fm );
    NOTE_ON_in = fi( NOTE_ON, 0, 1, 0, fm );
    ASR_IN_in = fi( ASR_IN, 1, 16, 0, fm );
    [ASR_OUT_out] = ASR_GEN_fixpt( ATTACK_CC_in, RELEASE_CC_in, MAX_ATTACK_MS_in, MAX_RELEASE_MS_in, CLK_FREQ_in, NOTE_ON_in, ASR_IN_in );
    ASR_OUT = double( ASR_OUT_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
