%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function y = andrew_filter_wrapper_fixpt(in,MIDI_CC_FREQ,CC_RES,type)
    fm = get_fimath();
    in_in = fi( in, 1, 16, 0, fm );
    MIDI_CC_FREQ_in = fi( MIDI_CC_FREQ, 0, 7, 0, fm );
    CC_RES_in = fi( CC_RES, 0, 7, 0, fm );
    type_in = fi( type, 0, 2, 0, fm );
    [y_out] = andrew_filter_fixpt( in_in, MIDI_CC_FREQ_in, CC_RES_in, type_in );
    y = double( y_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Nearest',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
