-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Asurans\Downloads\fac\tese\filter hdl coder matlab\codegen\andrew_filter\hdlsrc\andrew_filter_fixpt_pkg.vhd
-- Created: 2023-07-12 17:34:05
-- 
-- Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE andrew_filter_fixpt_pkg IS
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
END andrew_filter_fixpt_pkg;

